### ISSUE TITLE
link_root_nodes and add_command_node_to_list            are they doing the same?

### ISSUE THREAD

**Issue by panndabea** [lmangall/minishell#20]
int add_command_node_to_list(struct node_s **cmd, struct node_s **current_cmd, struct node_s *new_cmd)

seems to be doing the same as

void link_root_nodes(struct node_type_master *master_node)

**Comment by lmangall** [comment]
They don't.
link_root_nodes is a level above add_command_node_to_list.
what add_command_node_to_list do is essential for the execution, what link_root_nodes do is extra: I think we don't eve use this functionality. It is good to look at the Miro image to understand what theese functions do.
