### ISSUE TITLE
logical operator "AND" : "&&" doesn't work

### ISSUE THREAD

**Issue by lmangall** [lmangall/minishell#31]
but maybe shouldn't, I didn't checked the subject

**Comment by panndabea** [comment]
That’s in the bonus ;)

Von meinem iPhone gesendet

**Comment by lmangall** [comment]
Bonus

**Comment by panndabea** [comment]
---------- Forwarded message ---------
From: WeTransfer ***@***.***>
Date: Wed, Jan 3, 2024 at 1:37 PM
Subject: ***@***.*** hat dir minishell über WeTransfer gesendet
To: ***@***.***>


This transfer expires on 2024-01-10
[image: Click 'Download images' to view images]
<https://wetransfer.com/?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid>
***@***.***
hat dir minishell gesendet
1 Objekt, 8 MB insgesamt ・ Läuft am 10 Januar, 2024 ab

*minishell * signals work
Hole dir deine Dateien
<https://wetransfer.com/downloads/1459196140b79945a62f848b6fff8af620240103123702/6239518430ccab3996ebdd77a28b399920240103123716/2727fa?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid>

Download-Link
https://wetransfer.com/downloads/1459196140b79945a62f848b6fff8af620240103123702/6239518430ccab3996ebdd77a28b399920240103123716/2727fa
<https://wetransfer.com/downloads/1459196140b79945a62f848b6fff8af620240103123702/6239518430ccab3996ebdd77a28b399920240103123716/2727fa?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid>
1 Objekt

minishell
Ordner・13 Objekte

Um sicherzustellen, dass unsere E-Mails ankommen, füge bitte
***@***.*** zu deinen Kontakten
<https://wetransfer.zendesk.com/hc/en-us/articles/204909429?utm_campaign=TRN_TDL_01&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_01>
hinzu.
Über WeTransfer
<https://wetransfer.com/about?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid>
  ・   Hilfe
<https://wetransfer.zendesk.com/hc/en-us?utm_campaign=TRN_TDL_01&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_01>
  ・   Rechtliche Hinweise
<https://wetransfer.com/legal/terms?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid>
  ・   Diese Übertragung als Spam melden
<https://wetransfer.zendesk.com/hc/en-us/requests/new?ticket_form_id=360000007663&utm_campaign=TRN_TDL_01&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_01&token=eyJhbGciOiJub25lIn0.eyJyZXF1ZXN0X3N1YmplY3QiOiJEaWVzZSDDnGJlcnRyYWd1bmcgYWxzIFNwYW0gbWVsZGVuIiwicmVxdWVzdF9kZXNjcmlwdGlvbiI6Imh0dHBzOi8vd2V0cmFuc2Zlci5jb20vZG93bmxvYWRzLzE0NTkxOTYxNDBiNzk5NDVhNjJmODQ4YjZmZmY4YWY2MjAyNDAxMDMxMjM3MDIvNjIzOTUxODQzMGNjYWIzOTk2ZWJkZDc3YTI4YjM5OTkyMDI0MDEwMzEyMzcxNi8yNzI3ZmEiLCJyZXF1ZXN0X2N1c3RvbV9maWVsZHNfMzYwMDAwMTcxMjIzIjoiN2FjYTJiZGY0NTg1YzU5NjJjOGE0MDlhZGJhNWJiODZiYmVkYjY5OTk1YTI1MWU3OWIxOTQ2MGQwMWE1Y2E3MDI5OTBmZTFjYjM0Y2Y2MzVmNjUxOTVjN2IxZDQ3MDJlMWJlNDc4YTU2Mzg0ODE1M2QxYjNjMjk3N2ZjZjBhNjYifQ.>
